-- Extra profile columns needed by ProfilePage & ProfileWizard
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS height           INTEGER,
  ADD COLUMN IF NOT EXISTS body_type        TEXT,
  ADD COLUMN IF NOT EXISTS eye_color        TEXT,
  ADD COLUMN IF NOT EXISTS hair_color       TEXT,
  ADD COLUMN IF NOT EXISTS smoking          TEXT,
  ADD COLUMN IF NOT EXISTS drinking         TEXT,
  ADD COLUMN IF NOT EXISTS tattoos          TEXT,
  ADD COLUMN IF NOT EXISTS piercing         TEXT,
  ADD COLUMN IF NOT EXISTS education        TEXT,
  ADD COLUMN IF NOT EXISTS occupation       TEXT,
  ADD COLUMN IF NOT EXISTS relationship_goal TEXT,
  ADD COLUMN IF NOT EXISTS looking_for      TEXT[],
  ADD COLUMN IF NOT EXISTS sexual_preferences TEXT[],
  ADD COLUMN IF NOT EXISTS safe_sex         TEXT,
  ADD COLUMN IF NOT EXISTS sex_description  TEXT,
  ADD COLUMN IF NOT EXISTS likes_list       TEXT[],
  ADD COLUMN IF NOT EXISTS dislikes_list    TEXT[],
  ADD COLUMN IF NOT EXISTS face_verified    BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS profile_views    INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_likes      INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS matches_count    INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS mood             TEXT;
